@startuml

title Website

package "Map" {
  [OpenLayers]
  [OpenStreetMaps]
  [Bootstrap]
}

[About]

package "Ecosystem" {
}

[Burial]

[Quiz]

package "Blog" {
  [Bootstrap ]
  [MySQL]
  [Google Login]
}


package "Events" {
  [Google Login ]
  [Google Calendar API]
  [Bootstrap  ]
}

[OpenLayers] --> [OpenStreetMaps]
[OpenLayers] -[dotted]-> [Bootstrap]

@enduml
