@startuml

title Website

package "Mobile Map" {
  [OpenLayers]
  [OpenStreetMaps]
  [Bootstrap]
}

[About]

package "Ecosystem" {
}

[Burial]

[Quiz]

[Header Bar]

[Map]

package "Blog" {
  [Bootstrap ]
  [MySQL]
  [Google Login]
}


package "Events" {
  [Google Login ]
  [Google Calendar API]
  [Bootstrap  ]
}

[OpenLayers] --> [OpenStreetMaps]
[OpenLayers] -[dotted]-> [Bootstrap]
[Header Bar] --> [About]
[Map] --> [Mobile Map]
[Header Bar] --> [Map]
[Header Bar] --> [Burial]
[Header Bar] --> [Quiz]
[Header Bar] --> [Ecosystem]
[Header Bar] --> [Blog]
[Header Bar] --> [Events]

@enduml
